apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-k8s-deployment
  namespace: nestjs-k8s
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nestjs-k8s
  template:
    metadata:
      labels:
        app: nestjs-k8s
    spec:

      containers:
      - name: nestjs-k8s
        image: nestjs-k8s
        imagePullPolicy: Never
        ports:
        - name:  nestjs-k8s-port
          containerPort: 3000
        resources:
          requests:
            memory: "128Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "1000m"